version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - processor
    networks:
      - vidisnap-network

  processor:
    build: ./processor
    networks:
      - vidisnap-network

networks:
  vidisnap-network:
    driver: bridge 