services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - processor
    networks:
      - vidisnap-network

  processor:
    build: ./processor
    networks:
      - vidisnap-network

  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - VIDISNAP_BACKEND_URL=http://processor:8000
      - VIDISNAP_TIMEOUT=120
    depends_on:
      - processor
    networks:
      - vidisnap-network

networks:
  vidisnap-network:
    driver: bridge 